Cherry pick of b58a68a7751efae227e12d8a736baf378c968830 failed
stdout:
Auto-merging l10n_ar_purchase/views/purchase_report_templates.xml
Auto-merging l10n_ar_purchase/i18n/es.po
Auto-merging l10n_ar_purchase/__manifest__.py
CONFLICT (content): Merge conflict in l10n_ar_purchase/__manifest__.py

stderr:
13:46:21.125899 git.c:444               trace: built-in: git cherry-pick b58a68a7751efae227e12d8a736baf378c968830
error: could not apply b58a68a7... [IMP] l10n_ar_purchase: show only vat tax
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status: