[TEMP] fix error in log other modules
2023-10-20 18:33:49,830 133 INFO ? odoo.modules.loading: skipping reset_modules_state, ir_module_module table does not exists
2023-10-20 18:33:49,830 133 ERROR ? odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/home/odoo/custom/odoo/odoo/modules/module.py", line 348, in load_manifest
    manifest['version'] = adapt_version(manifest['version'])
  File "/home/odoo/custom/odoo/odoo/modules/module.py", line 451, in adapt_version
    raise ValueError(f"Invalid version {base_version!r}. Modules should have a version in format `x.y`, `x.y.z`,"
ValueError: Invalid version '16.0.1.0.0'. Modules should have a version in format `x.y`, `x.y.z`, `16.5.x.y` or `16.5.x.y.z`.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/custom/odoo/odoo/modules/registry.py", line 113, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/custom/odoo/odoo/modules/loading.py", line 397, in load_modules
    odoo.modules.db.initialize(cr)
  File "/home/odoo/custom/odoo/odoo/modules/db.py", line 44, in initialize
    info = odoo.modules.get_manifest(i)
  File "/home/odoo/custom/odoo/odoo/modules/module.py", line 368, in get_manifest
    return load_manifest(module, mod_path)
  File "/home/odoo/custom/odoo/odoo/modules/module.py", line 350, in load_manifest
    raise ValueError(f"Module {module}: invalid manifest") from e
ValueError: Module l10n_ar_bank: invalid manifest
2023-10-20 18:33:49,831 133 CRITICAL ? odoo.service.server: Failed to initialize database `master_ar_reports`.
Traceback (most recent call last):
  File "/home/odoo/custom/odoo/odoo/modules/module.py", line 348, in load_manifest
    manifest['version'] = adapt_version(manifest['version'])
  File "/home/odoo/custom/odoo/odoo/modules/module.py", line 451, in adapt_version
    raise ValueError(f"Invalid version {base_version!r}. Modules should have a version in format `x.y`, `x.y.z`,"
ValueError: Invalid version '16.0.1.0.0'. Modules should have a version in format `x.y`, `x.y.z`, `16.5.x.y` or `16.5.x.y.z`.

The above exception was the direct cause of the following exception: