Cherry pick of 45606f932ff3c7745525afdc022891a918ec9df6 failed
stdout:
CONFLICT (add/add): Merge conflict in l10n_ar_purchase/views/purchase_report_templates.xml
Auto-merging l10n_ar_purchase/views/purchase_report_templates.xml
CONFLICT (add/add): Merge conflict in l10n_ar_purchase/i18n/l10n_ar_purchase.pot
Auto-merging l10n_ar_purchase/i18n/l10n_ar_purchase.pot
CONFLICT (add/add): Merge conflict in l10n_ar_purchase/i18n/es.po
Auto-merging l10n_ar_purchase/i18n/es.po
CONFLICT (add/add): Merge conflict in l10n_ar_purchase/__manifest__.py
Auto-merging l10n_ar_purchase/__manifest__.py

stderr:
19:11:59.270679 git.c:439               trace: built-in: git cherry-pick 45606f932ff3c7745525afdc022891a918ec9df6
error: could not apply 45606f93... [ADD] l10n_ar_purchase
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status: