Cherry pick of 8bb12c3190135fa8103985fc01ae6ba54581791a failed
stdout:
Auto-merging l10n_ar_withholding_ux/views/report_payment_receipt_templates.xml
CONFLICT (content): Merge conflict in l10n_ar_withholding_ux/views/report_payment_receipt_templates.xml

stderr:
14:32:01.801178 git.c:444               trace: built-in: git cherry-pick 8bb12c3190135fa8103985fc01ae6ba54581791a
error: could not apply 8bb12c31... [FIX] remove t-field-options not needed
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status: